apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fednot-backend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: fednot-backend
    spec:
      containers:
        - name: fednot-backend
          image: docker.io/dhubau/fednot-backend:latest
          imagePullPolicy: Always
          env:
            - name: PKS_BACKEND_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PKS_BACKEND_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PKS_BACKEND_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5