apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fednot-frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: fednot-frontend
    spec:
      containers:
        - name: fednot-frontend
          image: docker.io/dhubau/fednot-frontend:latest
          imagePullPolicy: Always
          env:
            - name: PKS_FRONTEND_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PKS_FRONTEND_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PKS_FRONTEND_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5